module.exports = [
    "acro sports",
    "competitive dancing",
    "cheerleading",
    "dancesport",
    "gymnastics",
    "air sports",
    "aerobatics",
    "air racing",
    "cluster ballooning",
    "hopper ballooning",
    "wingsuit flying",
    "gliding",
    "hang gliding",
    "powered hang glider",
    "human powered aircraft",
    "model aircraft",
    "parachuting",
    "banzai skydiving",
    "base jumping",
    "skydiving",
    "skysurfing",
    "wingsuit flying",
    "paragliding",
    "powered paragliding",
    "paramotoring",
    "ultralight aviation",
    "archery",
    "field archery",
    "flight archery",
    "gungdo",
    "indoor archery",
    "kyūdō",
    "popinjay",
    "target archery",
    "badminton",
    "ball badminton",
    "biribol",
    "bossaball",
    "fistball",
    "footbag net",
    "football tennis",
    "footvolley",
    "hooverball",
    "jianzi",
    "padel",
    "peteca",
    "pickleball",
    "platform tennis",
    "rocball",
    "sepak takraw",
    "sipa",
    "table tennis",
    "tennis",
    "throwball",
    "volleyball",
    "beach volleyball",
    "paralympic volleyball",
    "water volleyball",
    "wallyball",
    "basketball",
    "beach basketball",
    "deaf basketball",
    "streetball",
    "unicycle basketball",
    "water basketball",
    "wheelchair basketball",
    "cestoball",
    "korfball",
    "netball",
    "fastnet",
    "indoor netball",
    "ringball",
    "slamball",
    "bat-and-ball",
    "baseball",
    "softball",
    "slow pitch",
    "fast-pitch softball",
    "16-inch softball",
    "bat and trap",
    "british baseball – four posts",
    "brännboll",
    "corkball",
    "cricket",
    "indoor cricket",
    "limited overs cricket",
    "one day international",
    "test cricket",
    "twenty20",
    "danish longball",
    "elle",
    "kickball",
    "kilikiti",
    "lapta",
    "the massachusetts game – four bases",
    "matball",
    "oina",
    "old cat ",
    "over-the-line – qv",
    "palant",
    "pesäpallo",
    "punchball",
    "rounders",
    "scrub baseball",
    "stickball",
    "stool ball",
    "tee-ball",
    "town ball",
    "vigoro",
    "wireball",
    "wiffleball",
    "baton twirling",
    "baton twirling",
    "board sports",
    "skateboarding",
    "casterboarding",
    "freeboard",
    "longboarding",
    "streetboarding",
    "scootering",
    "skysurfing",
    "streetluge",
    "snowboarding",
    "mountainboarding",
    "sandboarding",
    "snowkiting",
    "surfing",
    "wakesurfing",
    "bodyboarding",
    "riverboarding",
    "skimboarding",
    "windsurfing",
    "wakeboarding",
    "kneeboarding",
    "paddleboarding",
    "catch games",
    "dodgeball",
    "ga-ga",
    "keep away",
    "kin-ball",
    "newcomb ball",
    "quidditch",
    "yukigassen",
    "climbing",
    "canyoning",
    "abseiling",
    "aid climbing",
    "ice climbing",
    "mixed climbing",
    "mountaineering",
    "rock climbing",
    "bouldering",
    "deep-water soloing",
    "sport climbing",
    "traditional climbing",
    "other",
    "canyoning",
    "coasteering",
    "hiking",
    "rope climbing",
    "pole climbing",
    "cycling",
    "bicycle",
    "artistic cycling",
    "bmx",
    "cyclo-cross",
    "cross-country mountain biking",
    "cycle polo",
    "cycle speedway",
    "downhill mountain biking",
    "dirt jumping",
    "freestyle bmx",
    "hardcourt bike polo",
    "road bicycle racing",
    "track cycling",
    "underwater cycling",
    "skibob",
    "skibobbing",
    "unicycle",
    "mountain unicycling",
    "street unicycling",
    "unicycling",
    "unicycle basketball",
    "unicycle hockey",
    "unicycle trials",
    "aiki-jūjutsu",
    "aikido",
    "jujutsu",
    "judo",
    "brazilian jiu-jitsu",
    "sambo",
    "sumo",
    "wrestling",
    "amateur wrestling",
    "greco-roman wrestling",
    "freestyle wrestling",
    "folk wrestling",
    "boli khela",
    "collar-and-elbow",
    "cornish wrestling",
    "dumog",
    "glima",
    "gouren",
    "kurash",
    "lancashire wrestling",
    "catch wrestling",
    "malla-yuddha",
    "mongolian wrestling",
    "pehlwani",
    "professional wrestling",
    "schwingen",
    "shuai jiao",
    "ssireum",
    "varzesh-e pahlavani",
    "yağlı güreş",
    "greek wrestling",
    "striking",
    "choi kwang-do",
    "cockfighting",
    "boxing",
    "bokator",
    "capoeira",
    "fujian white crane",
    "karate",
    "kenpō",
    "kickboxing",
    "lethwei",
    "muay thai",
    "pradal serey",
    "sanshou",
    "savate",
    "shaolin kung fu",
    "sikaran",
    "silat",
    "subak",
    "taekkyeon",
    "taekwondo",
    "taidō",
    "tang soo do",
    "wing chun",
    "mixed or hybrid",
    "baguazhang",
    "bando",
    "bartitsu",
    "bujinkan",
    "hapkido",
    "hwa rang do",
    "jeet kune do",
    "kajukenbo",
    "kalaripayattu",
    "krav maga",
    "kuk sool won",
    "marine corps martial arts program",
    "mixed martial arts",
    "northern praying mantis",
    "ninjutsu",
    "pankration",
    "pencak silat",
    "sanshou",
    "shidōkan karate",
    "shōrin-ryū shidōkan",
    "shoot boxing",
    "shootfighting",
    "shorinji kempo",
    "systema",
    "t'ai chi ch'uan",
    "vajra-mushti",
    "vale tudo",
    "vovinam",
    "xing yi quan",
    "zen bu kan kempo",
    "weapons",
    "axe throwing",
    "battōjutsu",
    "boffer fighting",
    "eskrima",
    "egyptian stick fencing",
    "fencing",
    "gatka",
    "hojōjutsu",
    "iaidō",
    "iaijutsu",
    "jōdō",
    "jogo do pau",
    "jūkendō",
    "jittejutsu",
    "kendo",
    "kenjutsu",
    "krabi–krabong",
    "kung fu",
    "kyūdō",
    "kyūjutsu",
    "modern arnis",
    "naginatajutsu",
    "nguni stick-fighting",
    "okinawan kobudō",
    "shurikenjutsu",
    "silambam",
    "sōjutsu",
    "sword fighting",
    "wushu",
    "kumdo",
    "wing chun",
    "skirmish",
    "airsoft",
    "laser tag",
    "paintball",
    "pool balls",
    "snooker",
    "carom billiards",
    "three-cushion",
    "five-pins",
    "balkline and straight rail",
    "cushion caroms",
    "four-ball",
    "artistic billiards",
    "novuss",
    "pocket billiards",
    "eight-ball",
    "blackball",
    "nine-ball",
    "straight pool",
    "one-pocket",
    "three-ball",
    "seven-ball",
    "ten-ball",
    "rotation",
    "baseball pocket billiards",
    "cribbage",
    "bank pool",
    "artistic pool",
    "trick shot competition",
    "speed pool",
    "bowlliards",
    "chicago",
    "kelly pool",
    "cutthroat",
    "killer",
    "russian pyramid",
    "snooker",
    "sinuca brasileira",
    "six-red snooker",
    "snooker plus",
    "hybrid carom–pocket games",
    "english billiards",
    "bottle pool",
    "cowboy",
    "obstacle variations",
    "bagatelle",
    "bar billiards",
    "bumper pool",
    "table sports",
    "foosball",
    "equine sports",
    "buzkashi",
    "barrel racing",
    "campdrafting",
    "cirit",
    "charreada",
    "chilean rodeo",
    "cross country",
    "cutting",
    "dressage",
    "endurance riding",
    "english pleasure",
    "equitation",
    "eventing",
    "equestrian vaulting",
    "gymkhana",
    "harness racing",
    "horse racing",
    "horseball",
    "hunter",
    "hunter-jumpers",
    "jousting",
    "pato",
    "reining",
    "rodeo",
    "show jumping",
    "steeplechase",
    "sur-papakh",
    "team penning",
    "tent pegging",
    "western pleasure",
    "fishing",
    "angling",
    "big-game fishing",
    "casting",
    "noodling",
    "spearfishing",
    "sport fishing",
    "surf fishing",
    "rock fishing",
    "fly fishing",
    "ice fishing",
    "flying disc sports",
    "disc dog",
    "disc golf",
    "disc golf",
    "dodge disc",
    "double disc court",
    "freestyle",
    "goaltimate",
    "guts",
    "flutterguts",
    "hot box",
    "ultimate",
    "football",
    "ancient games",
    "chinlone",
    "cuju",
    "episkyros",
    "harpastum",
    "kemari",
    "ki-o-rahi",
    "marn grook",
    "woggabaliri",
    "yubi lakpi",
    "medieval football",
    "ba game",
    "caid",
    "calcio fiorentino",
    "camping",
    "cnapan",
    "cornish hurling",
    "haxey hood",
    "knattleikr",
    "la soule",
    "lelo burti",
    "mob football",
    "royal shrovetide football",
    "uppies and downies",
    "association football",
    "jorkyball",
    "paralympic football",
    "powerchair football",
    "reduced variants",
    "five-a-side football",
    "beach soccer",
    "futebol de salão",
    "futsal",
    "papi fut",
    "indoor soccer",
    "masters football",
    "street football",
    "freestyle football",
    "keepie uppie",
    "swamp football",
    "three sided football",
    "australian football",
    "nine-a-side footy",
    "rec footy",
    "metro footy",
    "english school games",
    "eton college",
    "field game",
    "wall game",
    "harrow football",
    "gaelic football",
    "ladies' gaelic football",
    "gridiron football",
    "american football",
    "eight-man football",
    "flag football",
    "indoor football",
    "arena football",
    "nine-man football",
    "six-man football",
    "sprint football",
    "touch football",
    "canadian football",
    "street football",
    "rugby football",
    "beach rugby",
    "rugby league",
    "masters rugby league",
    "mod league",
    "rugby league nines",
    "rugby league sevens",
    "tag rugby",
    "touch football",
    "wheelchair rugby league",
    "rugby union",
    "american flag rugby",
    "mini rugby",
    "rugby sevens",
    "tag rugby",
    "touch rugby",
    "rugby tens",
    "snow rugby",
    "hybrid codes",
    "austus",
    "eton wall game",
    "international rules football",
    "samoa rules",
    "speedball",
    "universal football",
    "volata",
    "golf",
    "miniature golf",
    "match play",
    "skins game",
    "speed golf",
    "stroke play",
    "team play",
    "shotgun start",
    "urban golf",
    "gymnastics",
    "acrobatic gymnastics",
    "aerobic gymnastics",
    "artistic gymnastics",
    "balance beam",
    "floor",
    "high bar",
    "parallel bars",
    "pommel horse",
    "still rings",
    "uneven bars",
    "vault",
    "juggling",
    "rhythmic gymnastics",
    "ball",
    "club",
    "hoop",
    "ribbon",
    "rope",
    "rope jumping",
    "slacklining",
    "trampolining",
    "trapeze",
    "flying trapeze",
    "static trapeze",
    "tumbling",
    "handball family",
    "goalball",
    "tchoukball",
    "team handball",
    "beach handball",
    "czech handball",
    "field handball",
    "torball",
    "water polo",
    "hunting",
    "beagling",
    "big game hunting",
    "deer hunting",
    "fox hunting",
    "hare coursing",
    "wolf hunting",
    "ice sports",
    "bandy",
    "rink bandy",
    "barrel jumping",
    "broomball",
    "moscow broomball",
    "curling",
    "ice hockey",
    "ringette",
    "ice yachting",
    "figure skating",
    "single skating",
    "pair skating",
    "ice dancing",
    "kite sports",
    "kite buggy",
    "kite fighting",
    "kite landboarding",
    "kitesurfing",
    "parasailing",
    "snow kiting",
    "sport kite",
    "stunt kite",
    "mixed discipline",
    "adventure racing",
    "biathlon",
    "duathlon",
    "decathlon",
    "heptathlon",
    "icosathlon",
    "modern pentathlon",
    "pentathlon",
    "tetrathlon",
    "triathlon",
    "orienteering family",
    "geocaching",
    "orienteering",
    "rogaining",
    "letterboxing",
    "waymarking",
    "pilota family",
    "valencian pilota.",
    "american handball",
    "australian handball",
    "basque pelota",
    "jai alai",
    "fives",
    "eton fives",
    "rugby fives",
    "frisian handball",
    "four square",
    "gaelic handball",
    "jeu de paume",
    "palla",
    "patball",
    "valencian pilota",
    "badminton",
    "ball badminton",
    "basque pelota",
    "frontenis",
    "xare",
    "beach tennis",
    "matkot",
    "miniten",
    "padel",
    "paleta frontón",
    "pelota mixteca",
    "pickleball",
    "platform tennis",
    "qianball",
    "racketlon",
    "racquetball",
    "racquets",
    "real tennis",
    "soft tennis",
    "speed-ball",
    "eclipse ball",
    "speedminton",
    "squash",
    "hardball squash",
    "squash tennis",
    "stické",
    "table tennis",
    "tennis",
    "tennis polo",
    "remote control",
    "model aerobatics",
    "rc racing",
    "robot combat",
    "slot car racing",
    "bullriding",
    "miniature bull riding",
    "barrel racing",
    "bronc riding",
    "saddle bronc riding",
    "bareback bronc riding",
    "pole bending",
    "roping",
    "breakaway roping",
    "calf roping",
    "team roping",
    "steer roping",
    "steer wrestling",
    "goat tying",
    "running",
    "200 meters sprint",
    "endurance",
    "5k run",
    "10k run",
    "cross-country running",
    "half marathon",
    "marathon",
    "road running",
    "ekiden",
    "tower running",
    "ultramarathon",
    "snowshoe running",
    "fell running",
    "trail running",
    "mountain running",
    "skyrunning",
    "sprint",
    "hurdles",
    "sailing",
    "windsurfing",
    "ice yachting",
    "land sailing",
    "land windsurfing",
    "sailing",
    "windsurfing",
    "kiteboarding",
    "dinghy sailing",
    "snow sports",
    "skiing",
    "alpine skiing",
    "freestyle skiing",
    "nordic combined",
    "nordic skiing",
    "cross-country skiing",
    "telemark skiing",
    "ski jumping",
    "ski touring",
    "skijoring",
    "speed skiing",
    "bobsleigh",
    "luge",
    "skibobbing",
    "skeleton",
    "toboggan",
    "clay pigeon shooting",
    "skeet shooting",
    "trap shooting",
    "sporting clays",
    "target shooting",
    "field target",
    "fullbore target rifle",
    "high power rifle",
    "benchrest shooting",
    "metallic silhouette",
    "practical shooting",
    "cowboy action shooting",
    "metallic silhouette shooting",
    "stacking",
    "card stacking",
    "dice stacking",
    "sport stacking",
    "stick and ball games",
    "hornussen",
    "hockey",
    "hockey",
    "ball hockey",
    "bando",
    "bandy",
    "rink bandy",
    "broomball",
    "moscow broomball",
    "field hockey",
    "indoor field hockey",
    "floorball",
    "ice hockey",
    "pond hockey",
    "power hockey",
    "sledge hockey",
    "underwater ice hockey",
    "ringette",
    "rinkball",
    "roller hockey",
    "inline hockey",
    "roller hockey",
    "skater hockey",
    "rossall hockey",
    "spongee",
    "street hockey",
    "underwater hockey",
    "unicycle hockey",
    "hurling and shinty",
    "cammag",
    "hurling",
    "camogie",
    "shinty",
    "composite rules shinty-hurling",
    "lacrosse",
    "lacrosse",
    "box lacrosse",
    "field lacrosse",
    "women's lacrosse",
    "intercrosse",
    "bicycle polo",
    "canoe polo",
    "cowboy polo",
    "elephant polo",
    "horse polo",
    "segway polo",
    "yak polo",
    "street sports",
    "free running",
    "freestyle footbag",
    "freestyle football",
    "powerbocking",
    "parkour",
    "scootering",
    "street workout",
    "tag games",
    "british bulldogs",
    "capture the flag",
    "hana ichi monme",
    "hide and seek",
    "jugger",
    "kabaddi",
    "kho kho",
    "kick the can",
    "oztag",
    "red rover",
    "tag",
    "walking",
    "hiking",
    "backpacking",
    "racewalking",
    "bushwhacking",
    "walking",
    "wall-and-ball",
    "american handball",
    "australian handball",
    "basque pelota",
    "butts up",
    "chinese handball",
    "fives",
    "gaelic handball",
    "international fronton",
    "jorkyball",
    "racquetball",
    "squash",
    "squash tennis",
    "valencian frontó",
    "wallball",
    "wallyball",
    "aquatic & paddle sports",
    "canoeing",
    "canoeing",
    "outrigger canoeing",
    "kayaking",
    "creeking",
    "flyak",
    "freeboating",
    "sea kayaking",
    "squirt boating",
    "surf kayaking",
    "whitewater kayaking",
    "rafting",
    "white water rafting",
    "rowing",
    "gig racing",
    "coastal and ocean rowing",
    "surfboat",
    "single scull",
    "other paddling sports",
    "dragon boat racing",
    "stand up paddle boarding",
    "aquatic ball sports",
    "surface",
    "water polo",
    "canoe polo",
    "waboba",
    "underwater",
    "underwater football",
    "underwater rugby",
    "underwater hockey",
    "competitive swimming",
    "backstroke",
    "breaststroke",
    "butterfly stroke",
    "freestyle swimming",
    "individual medley",
    "synchronized swimming",
    "medley relay",
    "kindred activities",
    "bifins",
    "surface finswimming",
    "subsurface and recreational",
    "apnoea finswimming",
    "aquathlon",
    "freediving",
    "immersion finswimming",
    "scuba diving",
    "spearfishing",
    "snorkelling",
    "sport diving",
    "underwater hockey",
    "underwater orienteering",
    "underwater photography",
    "underwater target shooting",
    "diving",
    "cliff diving",
    "diving",
    "weightlifting",
    "bodybuilding",
    "highland games",
    "olympic weightlifting",
    "powerlifting",
    "strength athletics",
    "steinstossen",
    "crossfit",
    "motorized sports",
    "auto racing",
    "autocross",
    "slalom",
    "autograss",
    "banger racing",
    "board track racing",
    "demolition derby",
    "desert racing",
    "dirt track racing",
    "drag racing",
    "drifting",
    "folkrace",
    "formula racing",
    "formula libre",
    "formula student",
    "hillclimbing",
    "ice racing",
    "kart racing",
    "land speed records",
    "legends car racing",
    "midget car racing",
    "monster truck",
    "mud bogging",
    "off-road racing",
    "pickup truck racing",
    "production car racing",
    "race of champions",
    "rally raid",
    "rallycross",
    "rallying",
    "regularity rally",
    "road racing",
    "short track motor racing",
    "snowmobile racing",
    "sports car racing",
    "sprint car racing",
    "street racing",
    "stock car racing",
    "time attack",
    "tractor pulling",
    "touring car racing",
    "truck racing",
    "vintage racing",
    "wheelstand competition",
    "motorboat racing",
    "drag boat racing",
    "f1 powerboat racing",
    "hydroplane racing",
    "jet sprint boat racing",
    "offshore powerboat racing",
    "personal water craft",
    "motorcycle racing",
    "motogp racing",
    "auto race",
    "board track racing",
    "cross-country rally",
    "endurance racing",
    "enduro",
    "freestyle motocross",
    "grand prix motorcycle racing",
    "grasstrack",
    "hillclimbing",
    "ice racing",
    "ice speedway",
    "indoor enduro",
    "motocross",
    "motorcycle drag racing",
    "motorcycle speedway",
    "off-roading",
    "rally raid",
    "road racing",
    "superbike racing",
    "supercross",
    "supermoto",
    "supersport racing",
    "superside",
    "track racing",
    "trial",
    "tt racing",
    "free-style moto",
    "atv racing",
    "marker sports",
    "airsoft",
    "archery",
    "paintball",
    "darts",
    "fantasy sports",
    "quidditch",
    "hunger games",
    "rocket league",
    "other",
    "stihl timbersports series",
    "woodsman",
    "overlapping sports",
    "tennis",
    "polocrosse",
    "badminton",
    "polo",
    "card games",
    "other",
    "debating",
    "quizzing",
    "speedcubing",
    "speedcubing",
    "2x2x2",
    "3x3x3",
    "3x3x3 one-handed",
    "4x4x4",
    "5x5x5",
    "6x6x6",
    "7x7x7",
    "megaminx",
    "pyraminx",
    "rubik's clock",
    "skewb",
    "square-1",
    "arimaa",
    "backgammon",
    "chess",
    "chess",
    "losing chess",
    "checkers",
    "chinese checkers",
    "diplomacy",
    "dominoes",
    "draughts",
    "go",
    "go-moku",
    "jacquet",
    "mancala",
    "mahjong",
    "reversi",
    "risk",
    "scrabble",
    "shogi",
    "sholo guti",
    "sogo",
    "stratego",
    "sudoku",
    "xiangqi",
    "chinese chess",
    "competitive model sports",
    "model aircraft racing",
    "model yacht racing",
    "neppis",
    "slot car racing",
    "banzai skydiving",
    "bungee jumping",
    "hot air ballooning",
    "pole vault",
    "steeplechase",
    "cross country",
    "jumping",
    "triple jump",
    "long jump",
    "high jump",
    "pole vault",
    "throwing",
    "discus",
    "hammer throw",
    "javelin",
    "shot put",
    "racewalking",
    "combat robot",
    "contesting",
    "geo caching",
    "radio-control vehicles",
    "video gaming",
    "endurance sports",
    "chariot racing",
    "cross-country skiing",
    "running",
    "cycling",
    "rowing",
    "swimming",
    "wheelchair racing",
    "wood chopping",
    "basketball",
    "football",
    "handball",
    "hockey",
    "lacrosse",
    "polo",
    "waterpolo",
    "quidditch",
    "skating sports",
    "aggressive inline skating",
    "artistic roller skating",
    "figure skating",
    "freestyle slalom skating",
    "ice dancing",
    "ice skating",
    "inline speed skating",
    "rinkball",
    "rink hockey",
    "roller derby",
    "roller skating",
    "short track speed skating",
    "skater hockey",
    "speed skating",
    "synchronized skating",
    "boardercross",
    "freestyle snowboarding",
    "freestyle skiing",
    "snowboarding",
    "ski flying",
    "skibob",
    "snowshoe running",
    "skiboarding",
    "arm wrestling",
    "olympic weightlifting",
    "powerlifting",
    "rock climbing",
    "strongman",
    "thumb wrestling",
    "toe wrestling",
    "tug-o-war",
    "wood chopping",
    "wood splitting",
    "zourkhaneh",
    "table sports",
    "air hockey",
    "backgammon",
    "beer pong",
    "connect four",
    "cue sports",
    "draughts",
    "dominoes",
    "headis",
    "janggi",
    "mahjong",
    "reversi",
    "shogi",
    "scrabble",
    "subbuteo",
    "table football",
    "table hockey",
    "table tennis",
    "xiangqi",
    "target sports",
    "sports where the main objective is to hit a certain target.",
    "archery",
    "axe throwing",
    "bocce",
    "bocce volo",
    "boccia",
    "bolas criollas",
    "boules",
    "bowling",
    "bowls a.k.a. lawn bowls",
    "calva",
    "cornhole",
    "croquet",
    "cue sports",
    "darts",
    "golf",
    "knife throwing",
    "kubb",
    "matball",
    "mölkky",
    "pall mall",
    "pétanque",
    "pitch and putt",
    "ring-goal",
    "shooting",
    "shuffleboard",
    "skittles",
    "skee ball",
    "tournament of knights",
    "trugo",
    "woodball",
    "lacrosse",
    "basketball family",
    "bat and ball games",
    "bowling",
    "basque pelota",
    "bunnock",
    "camogie",
    "football family",
    "gateball",
    "handball",
    "hardcourt bike polo",
    "hockey family",
    "horseshoe",
    "hurling",
    "kickball",
    "lacrosse",
    "mesoamerican ballgame",
    "newcomb ball",
    "polo",
    "paintball",
    "quidditch",
    "ringette",
    "rowing",
    "sepak takraw",
    "underwater football",
    "woodsman",
    "volleyball",
    "windsports",
    "kite flying",
    "parachuting",
    "hot air balloon racing",
    "fictional sports",
    "43-man squamish",
    "calvinball",
    "quidditch",
    "guyball",
    "logrolling",
    "chess boxing",
    "competitive eating",
    "egg and spoon race",
    "extreme ironing",
    "ferret legging",
    "fierljeppen",
    "footbag",
    "hacky sack",
    "haggis hurling",
    "lumberjack sports",
    "aizkolaritza",
    "axe throwing",
    "logrolling",
    "wood chopping",
    "wood splitting",
    "marching band",
    "patball",
    "ring-goal",
    "ringette",
    "sack race",
    "soap shoes",
    "tennikoit",
    "tetherball",
    "three-legged race",
    "wallball",
    "wife-carrying",
    "yoyoing",
    "object spinning",
    "plate spinning",
    "padiddling"
 ];